### ISSUE TITLE
Add PartialObjects instead of PlainObjects

### ISSUE THREAD

**Issue by aexol** [graphql-editor/graphql-zeus#116]
Add Partial objects with all optional fields as an export so you can use them somewhere in frontend

**Comment by bmestanov** [comment]
Hi, why was this issue closed? I'm running into a situation that I would need the objects to be partial. Here's the case:

I have a model that I query like this:

```ts
// Reviews.tsx
useTypedLazyQuery(
    {
      allReviews: [
        {},
        {
          totalCount: true,
          items: {
            id: true,
            // ...
            onlineProfile: {
              id: true,
              // ...
            },
          },
        },
      ],
    }
  );
```

I get the list of reviews in `data`, and I need to render them in a list. The important thing here is that, I want to be able to type the child component's props.

```ts
// ReviewCard.tsx
type Props = {
  review: // ?
}

export default function ReviewCard({ review }: Props) {
  // ...
}
```

I tried using `ModelTypes['Review']` but it's problematic because I don't select all fields I can possibly select, like `Review.subReviews[]`. Furthermore, I have `Review` fields that are non-nullable, but I just don't select them. The type error prevents me from passing the result of the query into the child component. I think if all model types were `Partial<T>`, I would not have this issue.

Am I not using the generated code properly? Maybe there is a pattern I am not seeing here. Thanks!

**Comment by aexol** [comment]
Oh so I see bigger need for other type `Select`
So you could do:
```ts
import { ResponseTypeSelector } from './zeus'

const a = Selectors.query({publicQuery:{getStory:[{storyId:'s'},{id:true}]}})
type TheRealTypeYouGetFromGraphQL =  ResponseTypeSelector<typeof a, GraphQLTypes['Query']>

```

Does it make sense?

**Comment by bmestanov** [comment]
Thanks for the swift response, I am not sure what `ResponseTypeSelector` is here, but I saw you updated the docs to reflect this case 🙌. I'm still having an issue with it, though. This is the code:

```ts
  import { GraphQLTypes, InputType, Selectors } from './generated/zeus';
  const selector = Selectors.query({
    allAccounts: { id: true, title: true },
  });

  type InferredResponseType = InputType<typeof selector, GraphQLTypes['Query']>;
```

It's essentially copied from https://github.com/graphql-editor/graphql-zeus#inferring-the-response-type

But the InferredResponseType is not what I expect:

<img width="778" alt="изображение" src="https://user-images.githubusercontent.com/17569192/133755347-f0d866d8-a112-4412-81b2-2540640d44c9.png">

Every query has type `never`, including the one that comes from the selector.

Using TS version 4.4.2.

**Comment by aexol** [comment]
Ok so literally TS 4.4 broke the whole zeus. Now please wait 6 months for me to repair thanks @ahejlsberg and @microsoft for making breaking changes in every minor

**Comment by aexol** [comment]
do you have `3.2.0` ?

**Comment by aexol** [comment]
of zeus

**Comment by bmestanov** [comment]
Yes, it's 3.2.0

**Comment by aexol** [comment]
InputType<GraphQLTypes['Query'],typeof selector>;

**Comment by aexol** [comment]
have you tried?

**Comment by aexol** [comment]
:D

**Comment by bmestanov** [comment]
Works! Thanks 👌

**Comment by aexol** [comment]
It was a mistake in readme @bmestanov

**Comment by aexol** [comment]
Thanks a lot ! 🚀

**Comment by aexol** [comment]
@pedrosimao Can you show me a full example? I can't debug with that

**Comment by pedrosimao** [comment]
Hi @aexol, I tried many things and now the problem seems fixed on my side. I worked till 5 in the morning yesterday trying to fix the issue and I tried multiple stuff without committing. Out of the blue, I saw it was suddenly working.  So, I don't exactly know how to reproduce it for you here. I have just tried (by undoing some of the stuff I did) and I still can't find what was it.

But I guess two things might have influenced:
1 - I updated Typecript version from `4.1.6` to `4.3.5`.
2 - On my custom hook (in which I use `react-query` `useHook`) I no longer pass options (type `UseQueryOptions`) as an argument. 

So, it would be great if `graphql-zeus` had its own implementation of react-query `useQuery`, just like it does with Apollo client. It's probably not hard to do and it would avoid `gaphhql-zeus` newbies like myself comeback here from time to time. I would love to help with that, but I still don't know graphql-zeus well enough. (I started using it only few days ago). If that might serve of some inspiration, here are my working custom hooks:

```
/*
 * User Query / Mutation
 */

// Selectors
export const userSelector = Selectors.query({
  user: {
    id: true,
    username: true,
    email: true,
    firstName: true,
    lastName: true,
    website: true,
    position: true,
    avatar: {
      id: true,
      url: true,
    },
    role: {
      id: true,
      name: true,
    },
  },
} as const)

// Types
export type UserQueryType = InputType<GraphQLTypes['Query'], typeof userSelector>
export type UserInputType = ValueTypes['UserInput']

// Query
export const useQueryUser = (id?: string) => {
  return useQuery(
    'user',
    () => {
      return typeof id !== 'undefined'
        ? chain()
            .query({
              user: [
                {
                  id,
                },
                userSelector.user,
              ],
            })
            .then((response) => response)
        : Promise.reject(new Error('Invalid id'))
    },
    {
      enabled: Boolean(id),
    },
  )
}

// Mutation
export const useMutateUser = () => {
  return useMutation(
    'user',
    async ({
      id,
      data,
    }: {
      id: string
      data: UserInputType
    }): Promise<UserQueryType | undefined> => {
      const { updateUser } = await chain().mutation({
        updateUser: [
          {
            input: {
              where: id ? { id } : undefined,
              data,
            },
          },
          userSelector,
        ],
      })
      return updateUser
    },
  )
}
```
