### ISSUE TITLE
Support for subscriptions

### ISSUE THREAD

**Issue by remorses** [graphql-editor/graphql-zeus#148]
The subscriptions types are present in the generated code but the fetcher cannot fetch subscriptions because it is a simple fetch wrapper.

To add support for subscription there should be an option in the `fetchFunction` called something like `isSubscription` and then the user could import a fetcher from `graphql-zeus` that supports subscriptions (so that bundle size does not increase for people not using them)

**Comment by bkniffler** [comment]
Not sure if its viable, but I think query generation + graphql client is just a lot to build. There is awesome graphql clients like urql and apollo who have solved the complexity that a good client needs, especially extendability, caching and subscriptions. Would love to see graphql-zeus being able to swap between any client and only really building the queries/mutations, instead of trying to become a one-stop solution.

**Comment by bkniffler** [comment]
Ah, it is very much possible to use zeus only to generate the queries: 
https://github.com/graphql-editor/graphql-zeus/issues/139#issuecomment-629811823

Thus also to use subscriptions.
