### ISSUE TITLE
Array variables are not supported

### ISSUE THREAD

**Issue by matej21** [graphql-editor/graphql-zeus#154]
When I use a variable where an array is expected, resulting variable type in a query is not an array

e.g.
for following query definition:
```
type Query {
  fetchArticles(ids: [Int!]!): Article[]
}
```

and this zeus query:
```
{
  fetchArticles: [
    {ids: $`ids`},
    {title: true},
  ], 
}
```
Zeus generates this query:
```
query($ids: Int!) {...}
```

**Comment by WonderPanda** [comment]
I am also running into this issue when passing variables to a mutation that expects an array

**Comment by n3v3rd1e** [comment]
Hello, there is still a bug, this fix is working only when both are required:

```
type Query {
  fetchArticles(ids: [Int!]!): Article[]
}
```

However for the following(probably stupid example, but you know, only the type is important):

```
type Query {
  fetchArticles(ids: [Int!]): Article[]
}
```


with the same query as above:

```
{
  fetchArticles: [
    {ids: $`ids`},
    {title: true},
  ], 
}
```

zeus generates:

```
query($ids: [Int]!) {...}
```

I've tried to create a pull request, but kinda got lost in how is your codebase generated, so the pull-request which fixed this bug
 #https://github.com/graphql-editor/graphql-zeus/commit/ab815f7876b3d6a48d7cb1a1c0e1a9dc15f01b47

has the following code in TypesPropsResolver function:

```
const isRequired = resolvedValue.required ? '!' : '';
let t = `${typeResolved}`;
if (isArray) {
  if (isArrayRequired) {
    t = `${t}!`;
  }
  t = `[${t}]`;
}
if (isRequired) {
  t = `${t}!`;
}
return `\$${value.split(`ZEUS_VAR$`)[1]}__ZEUS_VAR__${t}`;
```

instead of this:

```
const isRequired = resolvedValue.required ? '!' : '';
let t = `${typeResolved}`;
if (isRequired) {
  t = `${t}!`;
}
if (isArray) {
  t = `[${t}]`;
  if (isArrayRequired) {
    t = `${t}!`;
  }
}

return `\$${value.split(`ZEUS_VAR$`)[1]}__ZEUS_VAR__${t}`;
```
