### ISSUE TITLE
MapType not exported any more (v3)

### ISSUE THREAD

**Issue by bkniffler** [graphql-editor/graphql-zeus#187]
Just updated to latest zeus (major version) and noticed that MapType is not exported any more. Is that an error or on purpose?

Will there be some kind of changelog for breaking changes like these? 

Thanks!

**Comment by GavinRay97** [comment]
Also the root types of the schema (`query_root`, `mutation_root`, and `subscription_root`) are no longer exported types, updated and had to revert due because app no longer worked 🙁

![image](https://user-images.githubusercontent.com/26604994/109672051-a0c11b00-7b42-11eb-9928-08245e0b5855.png)

(The README needs an update to the React Apollo integration now as well since it relies on these)
