### ISSUE TITLE
null instead of undefined

### ISSUE THREAD

**Issue by imbroyury** [graphql-editor/graphql-zeus#262]
Hello @aexol, thanks for your amazing library.

The generated type for nullable fields in v4.0.4 is `... | undefined` while in reality the runtime type is `... | null`.

The issue was originally reported in https://github.com/graphql-editor/graphql-zeus/issues/171 and https://github.com/graphql-editor/graphql-zeus/issues/184 for v3, it came back and is reproduced in v4.0.4 https://github.com/graphql-editor/graphql-zeus/issues/171#issuecomment-1059293427, likely because of commit https://github.com/graphql-editor/graphql-zeus/commit/a338a8dd14344c0d39deaba67cf17514231347ad.

Can you give an update on this? Do you plan to replace `undefined` with `null`? Perhaps, in v5? If no, why?

**Comment by aexol** [comment]
Maybe some day with a flag later. Using nulls make using Zeus extremely painful

**Comment by imbroyury** [comment]
Thanks for your prompt reply 🙌

But isn't it ultimately a caveat of using a GraphQL API?
If a server is sending over `null` for a `null`able field as an indication of no value, a developer shouldn't lie to him/herself for convenience.

**Comment by aexol** [comment]
They should. It is much easier to manage those objects without nulls. However we can make a config file for zeus to maintain all those flags like nulls vs undefined

**Comment by ValentinH** [comment]
We are using Zeus heavily on our codebase with a patch to use `null` for nullable values. I don't understand what do you mean by "much easier"?

**Comment by imbroyury** [comment]
@aexol it seems like it's not just me, so can you please elaborate on the "much easier" part of `null` vs `undefined` for other users of the library? 🙂
very interested in your point of view on the problem

**Comment by aexol** [comment]
ok, if you have an object stored and you want to provide values from the frontend side, then every optional field if the type is inferred by Zeus has to be manually typed as `null` and that doesn't make sense at all. You could have just written types by hand.

https://zeus.graphqleditor.com/page/selector.html

**Comment by imbroyury** [comment]
@aexol sorry, I don't think I understand why "every optional field if the type is inferred by Zeus has to be manually typed as null"? can't Zeus infer types as `| null`?

**Comment by ValentinH** [comment]
@aexol for your example, if I need to insert something from the frontend, let's say a user, each field will be optional because `ValueTypes` is used:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/2678610/170716343-c71b35af-9b28-4591-beac-091036b6defe.png">


Data returned by the API is typed by the `GraphQLTypes` where the non-required field are typed as `null` (non-optional):
<img width="569" alt="image" src="https://user-images.githubusercontent.com/2678610/170716185-3d3a2ddb-1e2d-4b90-9122-e44c2e82fa6c.png">

**Comment by aexol** [comment]
I will provide an example when I will have time for that

**Comment by FilipChalupa** [comment]
@aexol do you have any updates please?

**Comment by GauBen** [comment]
I just ran into an issue because of this. `null` and `undefined` do not behave exactly the same:

```ts
const {x = 1, y = 2} = {x: undefined, y: null};
console.log(x, y); // 1, null
```

> – A developer shouldn't lie to theirself for convenience.
> – They should.

Absolutely not, this feature is breaking type safety.

**Comment by ValentinH** [comment]
@aexol would you accept a PR where we enable this to be configured via a flag? 

I've been maintaining a fork of v4 for a few months and most changes are now useless thanks to the nice changes of v5.
I've only this case + another (I'll create a dedicated issue) that avoids us to use the official version 😅

**Comment by GauBen** [comment]
@ValentinH Here is a small update to your diff: you need to update `MapType` to the following

```ts
export type MapType<SRC, DST, SCLR extends ScalarDefinition> = SRC extends null
  ? null
  : SRC extends DeepAnify<DST>
    ? IsInterfaced<SRC, DST, SCLR>
    : never;
```

Otherwise, the `Type | null` union gets its `null` smashed by `SRC extends DeepAnify<DST>`

[TypeScript playground](https://www.typescriptlang.org/play/?#code/C4TwDgpgBAIhFgIIDsCWAzEAeAKgPigF4oBvKAbQAUpVkoBrCEAe3ShwF0B+ALigENkIKAF8A3ACgJoSFADyAJ1QBzWvwA2AWX5gc4CFgDKAJQDCAGliH8RKCdNQIAD2ARkAEwDOseEjSYsGGsCLjszKD5kCAA3CAVJaX0oADFUJwh3bV19IzNLIJtie0cXNy8oZABXdXUJKChQqpq6iLCHZ1cPbzgEFAxsArwW+tD7Ydao2PipGWgADVtFFTUtHT1ILDJUdz5PYCVkZVEoAB8K6vVLLZ2ofcroESGAeif6qAA9LhmkgE1bVPSmTWOWuu32tCOIlO5xqVxoNzuD2er3qnwkQA)

It would be nice to have this fixed directly in Zeus :)

**Comment by ValentinH** [comment]
Thanks for sharing this.

FWIW we have decided to migrate to https://the-guild.dev/graphql/codegen as the Zeus codegen size was getting way too big for us (and for Next.js, tsc and VSCode 😅). Also being able to author real Graphql is in the end is win as we don't have to teach yet another tech to the team and we can benefit from more tooling.

**Comment by GauBen** [comment]
I was thinking of making the same move for a while now, but with [Houdini](https://houdinigraphql.com/) taking care of the plumbing. Thanks for your tip!

**Comment by ValentinH** [comment]
Interesting approach!

**Comment by aexol** [comment]
done!!!! Nulls are in responses - also enums are standard not const

**Comment by GauBen** [comment]
You're awesome @aexol, thank you!
