### ISSUE TITLE
Does Zues support the GraphQL over WebSocket Protocol?

### ISSUE THREAD

**Issue by tintin10q** [graphql-editor/graphql-zeus#288]
I am using [Hasura](https://hasura.io) to manage my graphQL. As per [their docs](https://hasura.io/docs/latest/graphql/core/databases/postgres/subscriptions/index/) Hasura uses the [GraphQL over WebSocket Protocol](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md) made by the Apollo people. 

I actually had no idea that there was a special protocol for this but it makes sense. After I tried to make a subscription with Zeus and it did not work I looked under the hood in index.ts and saw found code:

```ts
export const apiSubscription = (options: chainOptions) => (query: string) => {
  try {
    const queryString = options[0] + '?query=' + encodeURIComponent(query);
    const wsString = queryString.replace('http', 'ws');
    const host = (options.length > 1 && options[1]?.websocket?.[0]) || wsString;
    const webSocketOptions = options[1]?.websocket || [host];
    const ws = new WebSocket(...webSocketOptions);
    return {
      ws,
      on: (e: (args: any) => void) => {
        ws.onmessage = (event: any) => {
          if (event.data) {
            const parsed = JSON.parse(event.data);
            const data = parsed.data;
            return e(data);
          }
        };
      },
      off: (e: (args: any) => void) => {
        ws.onclose = e;
      },
      error: (e: (args: any) => void) => {
        ws.onerror = e;
      },
      open: (e: () => void) => {
        ws.onopen = e;
      },
    };
  } catch {
    throw new Error('No websockets implemented');
  }
};
```

So if I understand this correctly you basically make a Subscription() with a link and then a query just like when using Chain but then Zeus will generate a string with the query as a qeury on the url and create the websocket connection. 
What I didn't realize because it was not in the docs was that the Subscription function returns this object with .on .open .error .off and  also the ws object. So this leads me to assume that I am supposed to implement my own protocol with this. 

Is that indeed the idea? Is the idea that people implement their own protocol? If so has anyone implemented the GraphQL over WebSocket Protocol with Zues? Or am I missing something? I saw the --appollo flag but to me it did not seem to include an GraphQL over WebSocket Protocol implementation.

If this is the idea is it even a good idea to put the subscription in the query string? Because on the one hand this project does not make assumptions about the subscription protocol and you are supposed to take care of it yourself but then also it does make the assumption that you want your query in the the url query parameter. But maybe that is how a lot of people do it I don't know.

Also I want to suggest putting the error at the end if it was catchted into the new Error because the reason that it failed might not be that there is no websockets implemented.

**Comment by tintin10q** [comment]
Maybe I typed a little bit too much on this issue. Could someone maybe reply with just a simple yes or no to the title.

**Comment by joserocha3** [comment]
@tintin10q I think it's a no. I found the same code you did, and it appears their example server uses URL parameters to make queries, and Hasura/Apollo does not.

**Comment by aexol** [comment]
Take a look at stuccoSubscriptions plugin and please do write same kind of plugin for the protocol you want

**Comment by GauBen** [comment]
> Take a look at stuccoSubscriptions plugin and please do write same kind of plugin for the protocol you want

I'm currently working on implementing [graphql-ws](https://github.com/enisdenjo/graphql-ws), but I'm not sure what's the best way to do it.

First of all, I'm using Zeus programmatically and it looks like this:

```ts
import { TranslateGraphQL } from 'graphql-zeus/lib/TranslateGraphQL/index.js';

const schema = await readFile('../schema.graphql', 'utf8');
const code = TranslateGraphQL.typescript({ schema });
await writeFile('./generated/client.ts', code);
```

I'm not using plugins because I currently don't need to, but plugins are hardcoded in [CLIClass.ts](https://github.com/graphql-editor/graphql-zeus/blob/db2df27f68403ef39a92153bdb6a4e9ba7609089/src/CLI/CLIClass.ts) making them unsuitable for programmatic use.

Zeus already has support for a kind of WS-based subscriptions thanks to [apiSubscription.ts](https://github.com/graphql-editor/graphql-zeus/blob/db2df27f68403ef39a92153bdb6a4e9ba7609089/src/TreeToTS/functions/new/apiSubscription.ts), but  it doesn't seem to be an implementation of neither [graphql-ws](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) nor [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md). May I rewrite this file to implement graphql-ws?

Also, the protocol is rather complex and has a reference implementation for both client- and server-side. It might be interesting to:

- let the user install a compatible version (Hinted by `optionalPeerDeps` or similar)
- add a typed wrapper around `graphql-ws.createClient`

rather than embed the whole lib in the resulting typescript files.

Please share all your ideas.

**Comment by tintin10q** [comment]
I think the client should have priority because often people also use a subscriptions solution hosted by someone else.

**Comment by tintin10q** [comment]
Maybe the subscriptions code should only be generated when a certain flag is set on the zeus cli. Like `--generate-ws-transport` or something like that. This could just be an input into the `TranslateGraphQL.typescript({shema, generate_ws_transport: false})`

This way the subscription code is only generated if need be. Instead of a boolean it could also take a string which specifies which protocol implementation should be generated. So like  `TranslateGraphQL.typescript({shema, generate_ws_transport: "graphql-ws"})` and `--generate-ws-transport=graphql-ws`. 

This should be clearly stated in the docs. Otherwise people have no idea.

**Comment by tintin10q** [comment]
Currently, I am using Zeus with Apollo client as well to be able to have subscriptions I would really to completely drop Apollo.
